name: Manual Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js は Firebase CLI のためだけにセットアップ（Functions を使わないなら不要かも）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Firebase へデプロイ
      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
