name: Manual Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js のセットアップ（CLI は Node.js 上で動くので必要）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Firebase CLI をグローバルインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Firebase Hosting にデプロイ
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
