name: PR Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Firebase CLI を入れる（Node.js は動作環境のためだけ）
      - name: Setup Node.js & Firebase CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g firebase-tools

      # プレビュー用チャネルにデプロイ
      - name: Deploy to Preview Channel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          CHANNEL_ID=pr-${{ github.event.number }}
          firebase hosting:channel:deploy $CHANNEL_ID \
            --expires 7d \
            --only hosting \
            --token $FIREBASE_TOKEN

      # プレビューURLをPRにコメント
      - name: Comment preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: .github/workflows/preview-url-template.txt
