name: PR Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Preview Channel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          CHANNEL_ID=pr-${{ github.event.number }}
          firebase hosting:channel:deploy $CHANNEL_ID \
            --expires 7d \
            --only hosting \
            --token $FIREBASE_TOKEN

      - name: Comment preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: .github/workflows/preview-url-template.txt
