# .github/workflows/preview-deploy.yml
name: Manual Preview Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js と Firebase CLI のセットアップ
      - name: Setup Node.js & Firebase CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g firebase-tools@latest

      # 3. Preview チャンネルにデプロイ
      - name: Deploy to Preview Channel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase hosting:channel:deploy preview \
            --expires 7d \
            --only hosting \
            --token $FIREBASE_TOKEN
