name: Manual Preview Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js & Firebase CLI
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install -g firebase-tools@latest

      - name: Deploy to Preview Channel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase hosting:channel:deploy preview \
            --project kgs-test-68924 \
            --config firebase.json \
            --expires 7d \
            --token $FIREBASE_TOKEN
